- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.stories.tsx
- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.test.tsx
- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.tsx
- src/components/integrated/OakQuizCheckBox/__snapshots__/OakQuizCheckBox.test.tsx.snap
- src/styles/theme/color.ts
- src/styles/theme/default.theme.ts
Implements new designs to visually represent the following states:
look at 
https://deploy-preview-45--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oakquizcheckbox--docs
- check all states rendered corrrectly
run 
```npm run test```
> feat: update OakQuizCheckbox feedback state

- src/components/base/InternalTextInput/InternalTextInput.stories.tsx
- src/components/base/InternalTextInput/InternalTextInput.test.tsx
- src/components/base/InternalTextInput/InternalTextInput.tsx
- src/components/base/InternalTextInput/__snapshots__/InternalTextInput.test.tsx.snap
- src/components/ui/OakTextInput/OakTextInput.stories.tsx
- src/components/ui/OakTextInput/OakTextInput.test.tsx
- src/components/ui/OakTextInput/OakTextInput.tsx
- src/components/ui/OakTextInput/__snapshots__/OakTextInput.test.tsx.snap
- src/components/ui/OakTextInput/index.ts
- src/components/ui/index.ts
Adds `OakTextInput` which will be used initially to enable free text input for quizzes 
Figma 👉🏼  https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=3854-11120&mode=dev
To review in Storybook 👉🏼 https://deploy-preview-47--lively-meringue-8ebd43.netlify.app/?path=/docs/components-ui-oaktextinput--docs
> feat(PUPIL-86) Add `OakTextInput`

- src/components/base/InternalTextInput/InternalTextInput.tsx
- src/components/base/InternalTextInput/__snapshots__/InternalTextInput.test.tsx.snap
- src/components/integrated/OakQuizTextInput/OakQuizTextInput.stories.tsx
- src/components/integrated/OakQuizTextInput/OakQuizTextInput.test.tsx
- src/components/integrated/OakQuizTextInput/OakQuizTextInput.tsx
- src/components/integrated/OakQuizTextInput/__snapshots__/OakQuizTextInput.test.tsx.snap
- src/components/integrated/OakQuizTextInput/index.ts
- src/components/ui/OakTextInput/OakTextInput.tsx
- src/components/ui/OakTextInput/__snapshots__/OakTextInput.test.tsx.snap
* Adds the `not-allowed` cursor to inputs when disabled
* Adds an `iconAlt` prop to `OakTextInput` so that we can deliver some context to AT with the icon
* Adds `OakQuizTextInput` which is a specialised form of `OakTextInput` configured with feedback states for quiizzes.
Builds upon the base `OakTextInput` as in Figma here 👇🏼 
https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=3854-11120&mode=dev
Can be found in Storybook here 👇🏼 
https://deploy-preview-51--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oakquiztextinput--docs
> feat(PUPIL-214) `OakQuizInput` component

- src/components/integrated/OakQuizRadioButton/OakQuizRadioButton.stories.tsx
- src/components/integrated/OakQuizRadioButton/OakQuizRadioButton.test.tsx
- src/components/integrated/OakQuizRadioButton/OakQuizRadioButton.tsx
- src/components/integrated/OakQuizRadioButton/__snapshots__/OakQuizRadioButton.test.tsx.snap
- src/components/integrated/OakQuizRadioButton/index.ts
- src/components/ui/OakRadioButton/OakRadioButton.tsx
- src/components/ui/OakRadioButton/__snapshots__/OakRadioButton.test.tsx.snap
- src/components/ui/OakRadioGroup/OakRadioGroup.test.tsx
- src/components/ui/OakRadioGroup/OakRadioGroup.tsx
- src/components/ui/OakRadioGroup/__snapshots__/OakRadioGroup.test.tsx.snap
Builds on `OakRadioButton` adding feedback and UI states as per the Figma design 👇🏼 
https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=3473-12269&mode=dev 
Storybook 👇🏼 
https://deploy-preview-56--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oakquizradiobutton--docs
> Feat(PUPIL-208): `OakQuizRadioButton`

- src/components/base/OakIcon/OakIcon.tsx
- src/components/ui/OakTextInput/OakTextInput.stories.tsx
- src/image-map.json
also updates the example for `OakTextInput` to use the new icons
https://deploy-preview-57--lively-meringue-8ebd43.netlify.app/?path=/docs/components-ui-oaktextinput--docs#with-icon
https://deploy-preview-57--lively-meringue-8ebd43.netlify.app/?path=/docs/components-ui-oaktextinput--docs#read-only-invalid-trailing-icon
> chore: add warning and update search icons for `OakIcon`

- src/components/integrated/OakQuizBottomNav/OakQuizBottomNav.stories.tsx
- src/components/integrated/OakQuizBottomNav/OakQuizBottomNav.tsx
- src/components/integrated/OakQuizBottomNav/__snapshots__/OakQuizBottomNav.test.tsx.snap
- src/components/ui/InternalRectButton/InternalRectButton.stories.tsx
- src/components/ui/InternalRectButton/InternalRectButton.tsx
- src/components/ui/InternalRectButton/__snapshots__/InternalRectButton.test.tsx.snap
- src/components/ui/OakPrimaryButton/OakPrimaryButton.tsx
- src/components/ui/OakPrimaryButton/__snapshots__/OakPrimaryButton.test.tsx.snap
- src/components/ui/OakSecondaryButton/OakSecondaryButton.tsx
- src/components/ui/OakSecondaryButton/__snapshots__/OakSecondaryButton.test.tsx.snap
* adds `width` and `maxWidth` props to `InternalRectButton`
* justifies the button content to the center
* sets the width of the example buttons to 100% in the bottom nav story
Storybook: https://deploy-preview-62--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oakquizbottomnav--docs
**Mobile**
**Above**
> feat(PUPIL-230): allow buttons to stretch to full width

- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.tsx
- src/components/integrated/OakQuizCheckBox/__snapshots__/OakQuizCheckBox.test.tsx.snap
This ensures that the `border-radius` for `OakQuizCheckbox` is applied inside the border
(as it is in Figma). This also ensures that the border does not subtract
from the width and height of the container so the layout is not impacted.
The other option is to switch to `content-box` and play with negative
margins which no one wants to do.
> fix(PUPIL-269) Align radio and checkbox styles

- src/components/ui/OakBackLink/OakBackLink.stories.tsx
- src/components/ui/OakBackLink/OakBackLink.test.tsx
- src/components/ui/OakBackLink/OakBackLink.tsx
- src/components/ui/OakBackLink/__snapshots__/OakBackLink.test.tsx.snap
- src/components/ui/OakBackLink/index.tsx
- src/components/ui/index.ts
a button or link to navigate back to the previous page in the user's journey. This component will initially be used in the top nav for the pupil lesson flow.
Storybook 👉🏼  https://deploy-preview-66--lively-meringue-8ebd43.netlify.app/?path=/docs/components-ui-oakbacklink--docs
> feat(PUPIL-256): add `OakBackLink` component

- src/components/base/OakIcon/OakIcon.tsx
- src/components/integrated/OakLessonTopNav/OakLessonTopNav.stories.tsx
- src/components/integrated/OakLessonTopNav/OakLessonTopNav.test.tsx
- src/components/integrated/OakLessonTopNav/OakLessonTopNav.tsx
- src/components/integrated/OakLessonTopNav/__snapshots__/OakLessonTopNav.test.tsx.snap
- src/components/integrated/OakLessonTopNav/index.ts
- src/components/integrated/OakQuizFeedback/index.ts
- src/components/integrated/index.ts
- src/image-map.json
This will render the navigation bar at the top of a lesson.
It includes slots for the back link and counter. These are included to keep the component dumb and leave it up to the host to decide how to hook up the back link and counter to the lesson state.
Figma 👉🏼  https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=4604-14267&mode=dev
Storybook 👉🏼 https://deploy-preview-67--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oaklessontopnav--docs 
A `mobileSummary` prop is included to allow the host to pass in alternate content when at the mobile breakpoint since the counter is not displayed.
**Mobile**
**Above**
> feat(PUPIL-229): add `OakLessonTopNav` component

- src/components/base/OakGrid/OakGrid.test.tsx
- src/components/base/OakGrid/OakGrid.tsx
`grid-column-gap` and `grid-row-gap` are deprecated names for `column-gap` and `row-gap`. They're still respected as aliases for the new property names but I suspect that is why they didn't appear in your test.
> fix(PUPIL-78): replace deprecated names for row and column gap

- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.stories.tsx
- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.test.tsx
- src/components/integrated/OakQuizCheckBox/OakQuizCheckBox.tsx
- src/components/integrated/OakQuizRadioButton/OakQuizRadioButton.stories.tsx
- src/components/integrated/OakQuizRadioButton/OakQuizRadioButton.test.tsx
- src/components/integrated/OakQuizRadioButton/OakQuizRadioButton.tsx
https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=3473%3A12270&mode=dev
https://deploy-preview-76--lively-meringue-8ebd43.netlify.app/?path=/story/components-integrated-oakquizradiobutton--with-feedback
https://deploy-preview-76--lively-meringue-8ebd43.netlify.app/story/components-integrated-oakquizcheckbox--feedback
> Fix/pupil 312/mcq feedback states

- src/components/integrated/OakLessonNavItem/OakLessonNavItem.stories.tsx
- src/components/integrated/OakLessonNavItem/OakLessonNavItem.test.tsx
- src/components/integrated/OakLessonNavItem/OakLessonNavItem.tsx
- src/components/integrated/OakLessonNavItem/__snapshots__/OakLessonNavItem.test.tsx.snap
- src/components/integrated/OakLessonNavItem/index.ts
- src/components/integrated/OakLessonTopNav/__snapshots__/OakLessonTopNav.test.tsx.snap
- src/components/integrated/index.ts
- src/components/ui/OakRoundIcon/OakRoundIcon.tsx
- src/image-map.json
Enables navigation to the given section of a lesson as well as displaying current progress in that section.
Figma 👉🏼  https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=4604-17936&mode=dev
Storybook 👉🏼 https://deploy-preview-70--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oaklessonnavitem--docs
**Tablet >=**
**Mobile**
> feat(PUPIL-257) `OakLessonNavItem`

- src/components/base/InternalButton/InternalButton.stories.tsx
- src/components/base/InternalButton/InternalButton.test.tsx
- src/components/base/InternalButton/InternalButton.tsx
- src/components/base/InternalButton/__snapshots__/InternalButton.test.tsx.snap
- src/components/integrated/OakHintButton/__snapshots__/OakHintButton.test.tsx.snap
- src/components/integrated/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/integrated/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
- src/components/ui/InternalRectButton/InternalRectButton.stories.tsx
- src/components/ui/InternalRectButton/InternalRectButton.test.tsx
- src/components/ui/InternalRectButton/InternalRectButton.tsx
- src/components/ui/InternalRectButton/__snapshots__/InternalRectButton.test.tsx.snap
- src/components/ui/InternalRoundButton/InternalRoundButton.stories.tsx
- src/components/ui/InternalRoundButton/InternalRoundButton.tsx
- src/components/ui/InternalRoundButton/__snapshots__/InternalRoundButton.test.tsx.snap
- src/components/ui/OakPrimaryButton/OakPrimaryButton.stories.tsx
- src/components/ui/OakPrimaryButton/OakPrimaryButton.tsx
- src/components/ui/OakPrimaryButton/__snapshots__/OakPrimaryButton.test.tsx.snap
- src/components/ui/OakSecondaryButton/OakSecondaryButton.stories.tsx
- src/components/ui/OakSecondaryButton/OakSecondaryButton.tsx
- src/components/ui/OakSecondaryButton/__snapshots__/OakSecondaryButton.test.tsx.snap
- src/components/ui/OakTertiaryButton/OakTertiaryButton.stories.tsx
- src/components/ui/OakTertiaryButton/OakTertiaryButton.tsx
- src/components/ui/OakTertiaryButton/__snapshots__/OakTertiaryButton.test.tsx.snap
- src/components/utils/polymorphic.ts
Convert button related components into polymorphic components so they can use any tag as a base tag. This will allow us to use them as links styled like buttons without duplicating the code.
Added relevant stories to Storybook.
> PUPIL-344 make button related components polymorphic

- src/components/integrated/OakLessonNavItem/OakLessonNavItem.tsx
- src/components/integrated/OakLessonNavItem/__snapshots__/OakLessonNavItem.test.tsx.snap
See https://github.com/oaknational/Oak-Web-Application/pull/2221#issuecomment-1923378463
* Fixes UA `color` being applied to `OakLessonNavItem` when presented as a `<button>` by making the `color` explicit
* Fixes the hover styles becoming stuck on touch devices (at least iOS) when the item is tapped.
Storybook 👉🏼  https://deploy-preview-95--lively-meringue-8ebd43.netlify.app/?path=/story/components-integrated-oaklessonnavitem--as-a-button
> PUPIL-283: Interaction state fixes for `OakLessonNavItem` to support the lesson overview page

- src/components/integrated/OakQuizTextInput/OakQuizTextInput.stories.tsx
- src/components/integrated/OakQuizTextInput/__snapshots__/OakQuizTextInput.test.tsx.snap
- src/components/ui/OakTextInput/OakTextInput.stories.tsx
- src/components/ui/OakTextInput/OakTextInput.tsx
- src/components/ui/OakTextInput/__snapshots__/OakTextInput.test.tsx.snap
The quiz text input should remain the same size when switching between input and feedback states . Currently it expands to accommodate the icon.
comments from designer:
“For the 2nd question of the starter quiz, and the 1st question of the exit quiz there is some shift in the size of the text input when submitting the question on desktop, and when the icon appears when in a valid or invalid state. The text input width shouldn't increase in width ideally across states. I think the width should be increased to something like 500px as a default for desktop. The text input should span the full width for tablet and mobile.” 
- Modify the underlying textInput so that setting the width adjusts the wrapper width rather than attempt (and fail) to adjust the input width
- change width prop on this …
> Fix/pupil 340/quiz text input widths

- src/components/integrated/OakHintButton/__snapshots__/OakHintButton.test.tsx.snap
- src/components/integrated/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/integrated/OakPrimaryNav/__snapshots__/OakPrimaryNav.test.tsx.snap
- src/components/integrated/OakPrimaryNavItem/__snapshots__/OakPrimaryNavItem.test.tsx.snap
- src/components/integrated/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
- src/components/ui/InternalShadowRectButton/InternalShadowRectButton.tsx
- src/components/ui/InternalShadowRectButton/__snapshots__/InternalShadowRectButton.test.tsx.snap
- src/components/ui/InternalShadowRoundButton/InternalShadowRoundButton.tsx
- src/components/ui/InternalShadowRoundButton/__snapshots__/InternalShadowRoundButton.test.tsx.snap
- src/components/ui/OakPrimaryButton/__snapshots__/OakPrimaryButton.test.tsx.snap
- src/components/ui/OakPrimaryInvertedButton/__snapshots__/OakPrimaryInvertedButton.test.tsx.snap
- src/components/ui/OakSecondaryButton/__snapshots__/OakSecondaryButton.test.tsx.snap
- src/components/ui/OakTertiaryButton/__snapshots__/OakTertiaryButton.test.tsx.snap
The buttons padding and spacing doesn't quite look to match the [[Figma component](https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=3029%3A11820&mode=dev)](https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=3029%3A11820&mode=dev) 
Also, can we check if the label of the button is using the correct FontToken - ‘heading-7’, as it looks to be bold when compared to the design kit in Figma.
- Actually this has been applied to all buttons as the issue was in the InternalButtons in the ui folder
https://deploy-preview-100--lively-meringue-8ebd43.netlify.app/?path=/docs/components-ui-internalshadowrectbutton--docs
https://deploy-preview-100--lively-meringue-8ebd43.netlify.app/?path=/docs/components-ui-internalshadowroundbutton--d …
> fix: style corrections for buttons

- src/components/base/OakGrid/OakGrid.stories.tsx
- src/components/base/OakGrid/OakGrid.tsx
this is a missing piece that lets us do a lot more with grid layouts.
I need this to properly layout the copyright notice on the lesson intro page.
> feat: add `grid-template-rows` prop to OakGrid component

- src/components/integrated/OakHintButton/__snapshots__/OakHintButton.test.tsx.snap
- src/components/integrated/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/integrated/OakLessonVideoTranscript/__snapshots__/OakLessonVideoTranscript.test.tsx.snap
- src/components/integrated/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
- src/components/ui/InternalShadowRoundButton/InternalShadowRoundButton.stories.tsx
- src/components/ui/InternalShadowRoundButton/InternalShadowRoundButton.tsx
- src/components/ui/InternalShadowRoundButton/__snapshots__/InternalShadowRoundButton.test.tsx.snap
- src/components/ui/OakTertiaryButton/__snapshots__/OakTertiaryButton.test.tsx.snap
http://localhost:6006/?path=/docs/components-ui-internalshadowroundbutton--docs
- Added a default display style of 'inline-block' to internalshadowroundbutton to override default style when element is set to link. 
- Ensures consitent behaviour between button and link versions.
> Fix/pupil 373/internal shadow round button default display prop

- src/components/integrated/OakLessonNavItem/OakLessonNavItem.stories.tsx
- src/components/integrated/OakLessonNavItem/OakLessonNavItem.test.tsx
- src/components/integrated/OakLessonNavItem/OakLessonNavItem.tsx
- src/components/integrated/OakLessonNavItem/__snapshots__/OakLessonNavItem.test.tsx.snap
- src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
- src/components/integrated/OakLessonReviewItem/__snapshots__/OakPupilLessonReviewItem.test.tsx.snap
Storybook: https://deploy-preview-106--lively-meringue-8ebd43.netlify.app/?path=/docs/components-integrated-oaklessonnavitem--docs
Figma: https://www.figma.com/file/G7z5ufo2T0CHk14CkadeuB/Pupils-high-fidelity-designs?type=design&node-id=2980-65763&mode=dev
> PUPIL-351: `OakLessonNavItem` copy changes

- src/components/integrated/OakHintButton/__snapshots__/OakHintButton.test.tsx.snap
- src/components/integrated/OakLessonBottomNav/OakLessonBottomNav.stories.tsx
- src/components/integrated/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/integrated/OakLessonVideoTranscript/__snapshots__/OakLessonVideoTranscript.test.tsx.snap
- src/components/integrated/OakPrimaryNav/__snapshots__/OakPrimaryNav.test.tsx.snap
- src/components/integrated/OakPrimaryNavItem/__snapshots__/OakPrimaryNavItem.test.tsx.snap
- src/components/integrated/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
- src/components/ui/InternalShadowRectButton/InternalShadowRectButton.tsx
- src/components/ui/InternalShadowRectButton/__snapshots__/InternalShadowRectButton.test.tsx.snap
- src/components/ui/InternalShadowRoundButton/InternalShadowRoundButton.tsx
- src/components/ui/InternalShadowRoundButton/__snapshots__/InternalShadowRoundButton.test.tsx.snap
- src/components/ui/OakPrimaryButton/__snapshots__/OakPrimaryButton.test.tsx.snap
- src/components/ui/OakPrimaryInvertedButton/__snapshots__/OakPrimaryInvertedButton.test.tsx.snap
- src/components/ui/OakSecondaryButton/__snapshots__/OakSecondaryButton.test.tsx.snap
- src/components/ui/OakTertiaryButton/__snapshots__/OakTertiaryButton.test.tsx.snap
- src/styles/theme/spacing.ts
* `min-content` and `max-content` are very useful.
* `max-content` seems like a sensible default for button widths (to prevent text wrapping)
* we should be able to safely apply this since the buttons are only currently used in the pupil section and none have intentional wrapping
* I will use this to prevent wrapping in `OakLessonBottomNav`
> feat(PUPIL-274): add missing sizing keywords and set a default button width

- package.json
The package.json had two licence fields, which caused npm to display the incorrect licence type
> chore: remove duplicate licence field

- scripts/prepublish.sh
This made sense when publishing locally but it now prevents the publish from happening in CI since the change to the version number isn't committed until after the publish is successful.
This should get automated publishing working 🤞
> chore: remove prepublish check for local changes

- .github/workflows/release.yml
- package.json
- scripts/prepublish.sh
This was a pain and I couldn't test it locally so it was a lot of trial and error — however I think it is finally working 🤞🏼
> chore: skip pre-commit hooks when creating a release

- src/components/CopyPasteThisComponent/CopyPasteThisComponent.stories.tsx
- src/components/CopyPasteThisComponent/CopyPasteThisComponent.test.tsx
- src/components/CopyPasteThisComponent/CopyPasteThisComponent.tsx
- src/components/CopyPasteThisComponent/__snapshots__/CopyPasteThisComponent.test.tsx.snap
- src/components/CopyPasteThisComponent/index.ts
created a new folder CopyPasteThisComponent
it is to be used as a template for new components which will hopefully help devs follow the conventions we have started for the library
the folder contains the following files
index.ts
CopyPasteThisComponent.tsx
CopyPasteThisComponent.stories.tsx
CopyPasteThisComponent.test.tsx
> PUPIL-459 feat(copy-paste-this): create template component folder and files

- pull_request_template.md
* Don't delete this text block *
> docs: updated PR template

- src/docs/designingComponents.mdx
- src/docs/tipsForReusableCode.mdx
Updated docs following mine and Carl's conversation this morning about best practice for reusing components
> docs: tips for resuble code

- .github/workflows/release.yml
🎉 releases are now being published to NPM.
However the bump commit to update package.json with the new version number cannot be pushed to `main` because the branch is protected.
Following this doc https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch I need someone with the power to add a repo secret `GITHUB_TOKEN` containing a Personal Access Token with the corresponding permissions to push to `main` bypassing the protected branch rules.
> chore: Allow CI to push updates to `package.json`

- src/components/molecules/OakDragAndDropInstructions/OakDragAndDropInstructions.tsx
- src/components/molecules/OakDragAndDropInstructions/__snapshots__/OakDragAndDropInstructions.test.tsx.snap
- src/components/organisms/pupil/OakQuizOrderQuestion/__snapshots__/OakQuizOrder.test.tsx.snap
- Check the design [Heuristics](https://lively-meringue-8ebd43.netlify.app/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://lively-meringue-8ebd43.netlify.app/?path=/docs/docs-namingconventions--docs) have been applied
- …
> feat(PUPIL-204): update drag and drop instructions

- src/components/atoms/OakIcon/OakIcon.tsx
- src/components/atoms/OakIcon/__snapshots__/OakIcon.test.tsx.snap
- src/components/molecules/InternalShadowRectButton/__snapshots__/InternalShadowRectButton.test.tsx.snap
- src/components/molecules/InternalShadowRoundButton/__snapshots__/InternalShadowRoundButton.test.tsx.snap
- src/components/molecules/OakBackLink/__snapshots__/OakBackLink.test.tsx.snap
- src/components/molecules/OakCheckBox/__snapshots__/OakCheckbox.test.tsx.snap
- src/components/molecules/OakDragAndDropInstructions/__snapshots__/OakDragAndDropInstructions.test.tsx.snap
- src/components/molecules/OakDraggable/__snapshots__/OakDraggable.test.tsx.snap
- src/components/molecules/OakDraggableFeedback/__snapshots__/OakDraggableFeedback.test.tsx.snap
- src/components/molecules/OakHandDrawnCardWithIcon/__snapshots__/OakHandDrawnCardWithIcon.test.tsx.snap
- src/components/molecules/OakLessonInfoCard/__snapshots__/OakLessonInfoCard.test.tsx.snap
- src/components/molecules/OakPrimaryButton/__snapshots__/OakPrimaryButton.test.tsx.snap
- src/components/molecules/OakPrimaryInvertedButton/__snapshots__/OakPrimaryInvertedButton.test.tsx.snap
- src/components/molecules/OakRoundIcon/__snapshots__/OakRoundIcon.test.tsx.snap
- src/components/molecules/OakSecondaryButton/__snapshots__/OakSecondaryButton.test.tsx.snap
- src/components/organisms/pupil/OakHintButton/__snapshots__/OakHintButton.test.tsx.snap
- src/components/organisms/pupil/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/organisms/pupil/OakLessonNavItem/__snapshots__/OakLessonNavItem.test.tsx.snap
- src/components/organisms/pupil/OakLessonReviewItem/__snapshots__/OakPupilLessonReviewItem.test.tsx.snap
- src/components/organisms/pupil/OakLessonTopNav/__snapshots__/OakLessonTopNav.test.tsx.snap
- src/components/organisms/pupil/OakLessonVideoTranscript/__snapshots__/OakLessonVideoTranscript.test.tsx.snap
- src/components/organisms/pupil/OakQuizFeedback/__snapshots__/OakQuizFeedback.test.tsx.snap
- src/components/organisms/pupil/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
- src/components/organisms/pupil/OakQuizMatch/__snapshots__/OakQuizMatch.test.tsx.snap
- src/components/organisms/pupil/OakQuizOrder/__snapshots__/OakQuizOrder.test.tsx.snap
> fix: icons shrinking when in a flex context

- src/components/molecules/OakTooltip/OakTooltip.stories.tsx
- src/components/molecules/OakTooltip/OakTooltip.test.tsx
- src/components/molecules/OakTooltip/OakTooltip.tsx
- src/components/molecules/OakTooltip/__snapshots__/OakTooltip.test.tsx.snap
> Fix tooltip positioning incorrectly inside a fixed element

- src/components/organisms/pupil/OakQuizMatch/OakQuizMatch.test.tsx
- src/components/organisms/pupil/OakQuizMatch/OakQuizMatch.tsx
- src/components/organisms/pupil/OakQuizMatch/__snapshots__/OakQuizMatch.test.tsx.snap
> PUPIL-546 Randomise options in `OakQuizMatch`

- src/components/atoms/InternalCheckBox/InternalCheckBox.tsx
- src/components/atoms/InternalCheckBox/__snapshots__/InternalCheckBox.test.tsx.snap
- src/components/atoms/OakP/OakP.tsx
- src/components/molecules/OakCheckBox/OakCheckBox.stories.tsx
- src/components/molecules/OakCheckBox/OakCheckBox.tsx
- src/components/molecules/OakCheckBox/__snapshots__/OakCheckbox.test.tsx.snap
- src/components/molecules/OakModal/OakModal.tsx
- src/components/molecules/OakModal/__snapshots__/OakModal.test.tsx.snap
- src/components/organisms/OakCookieBanner/OakCookieBanner.tsx
- src/components/organisms/OakCookieBanner/__snapshots__/OakCookieBanner.test.tsx.snap
- src/components/organisms/OakCookieConsent/__snapshots__/OakCookieConsent.test.tsx.snap
- src/components/organisms/OakCookieSettingsModal/OakCookieSettingsModal.tsx
- src/components/organisms/pupil/OakQuizCheckBox/__snapshots__/OakQuizCheckBox.test.tsx.snap
> Cookie modal design tweaks

- src/components/organisms/teacher/OakSearchFilterCheckBox/OakSearchFilterCheckBox.tsx
- src/components/organisms/teacher/OakSearchFilterCheckBox/__snapshots__/OaKSearchFilterCheckBox.test.tsx.snap
> Feat/ remove alt from search checkbox 

- src/components/atoms/index.ts
- src/components/organisms/teacher/OakTertiaryOLNav/OakTertiaryOLNav.stories.tsx
- src/components/organisms/teacher/OakTertiaryOLNav/OakTertiaryOLNav.test.tsx
- src/components/organisms/teacher/OakTertiaryOLNav/OakTertiaryOLNav.tsx
- src/components/organisms/teacher/OakTertiaryOLNav/__snapshots__/OakTertiaryOLNav.test.tsx.snap
- src/components/organisms/teacher/OakTertiaryOLNav/index.ts
- src/components/organisms/teacher/index.ts
> feat: order list nav with tertiary styling

- src/components/organisms/teacher/OakTertiaryOLNav/OakTertiaryOLNav.stories.tsx
- src/components/organisms/teacher/OakTertiaryOLNav/OakTertiaryOLNav.test.tsx
- src/components/organisms/teacher/OakTertiaryOLNav/OakTertiaryOLNav.tsx
- src/components/organisms/teacher/OakTertiaryOLNav/__snapshots__/OakTertiaryOLNav.test.tsx.snap
> feat: a11y aria current

- .storybook/main.ts
- src/components/atoms/OakAspectRatio/OakAspectRatio.tsx
- src/components/atoms/OakHeading/OakHeading.stories.tsx
- src/components/atoms/OakHeading/OakHeading.tsx
- src/styles/theme/color.ts
- src/styles/theme/typography.ts
Heading tag type used in OWA was degraded to string in the storybook upgrade, so this reinstates it as literal union. Ran check-types in OWA locally and not seeing any other issues. Had to defined the story control as select explicitly otherwise it infers text input type.
https://deploy-preview-174--lively-meringue-8ebd43.netlify.app/
> fix: export heading tags as const

- src/components/organisms/OakHeaderHero/OakHeaderHero.stories.tsx
- src/components/organisms/OakHeaderHero/OakHeaderHero.test.tsx
- src/components/organisms/OakHeaderHero/OakHeaderHero.tsx
- src/components/organisms/OakHeaderHero/__snapshots__/OakHeaderHero.test.tsx.snap
> Fix: Header alt text and spacing

- src/components/organisms/pupil/OakPupilJourneyList/OakPupilJourneyList.tsx
- src/components/organisms/pupil/OakPupilJourneyList/__snapshots__/OakPupilJourneyList.test.tsx.snap
- src/components/organisms/pupil/OakPupilJourneyListItem/OakPupilJourneyListItem.stories.tsx
- src/components/organisms/pupil/OakPupilJourneyListItem/OakPupilJourneyListItem.tsx
- src/components/organisms/pupil/OakPupilJourneyListItem/__snapshots__/OakPupilJourneyListItem.test.tsx.snap
> Fix/pupil 700/list aria roles

- src/components/organisms/pupil/OakPupilJourneyContentGuidance/OakPupilJourneyContentGuidance.test.tsx
- src/components/organisms/pupil/OakPupilJourneyContentGuidance/OakPupilJourneyContentGuidance.tsx
> fix: updated types on OakPupilJourneyContentGuidance

- src/components/molecules/OakModalCenter/OakModalCenter.tsx
- src/components/molecules/OakModalCenter/__snapshots__/OakModalCenter.test.tsx.snap
> fix: remove styled prop and change to styled component

- src/components/organisms/OakCookieBanner/OakCookieBanner.tsx
- src/components/organisms/OakCookieConsent/OakCookieConsent.tsx
- src/styles/helpers/parseZIndex.ts
- src/styles/helpers/parseZindex.test.tsx
- src/styles/theme/zIndex.ts
- src/styles/utils/zIndexStyle.ts
> fix: set cookie consent banner to 9999 z-index if fixed

- src/components/organisms/pupil/OakQuizMatch/OakQuizMatch.tsx
This PR fixes a type issue. Means that the mathjax component can be passed into the OakQuizMatch component on the label prop.
I don't have anyone else in my team for the next 2 weeks so apologies for asking outside the usual channels 🙂
See this PR if you are interested in output
https://github.com/oaknational/Oak-Web-Application/pull/2348
- …
> fix: allow labels to be react elements so that mathjax component can be passed in as label

- src/components/atoms/InternalTooltip/InternalTooltip.test.tsx
- src/components/atoms/InternalTooltip/InternalTooltip.tsx
- src/components/atoms/InternalTooltip/__snapshots__/InternalTooltip.test.tsx.snap
- src/components/molecules/OakTooltip/OakTooltip.test.tsx
- src/components/molecules/OakTooltip/OakTooltip.tsx
- src/components/molecules/OakTooltip/__snapshots__/OakTooltip.test.tsx.snap
- src/components/organisms/pupil/OakHintButton/OakHintButton.test.tsx
- src/components/organisms/pupil/OakHintButton/OakHintButton.tsx
- src/components/organisms/pupil/OakHintButton/__snapshots__/OakHintButton.test.tsx.snap
- src/components/organisms/pupil/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/organisms/pupil/OakQuizHint/OakQuizHint.tsx
- src/components/organisms/pupil/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
- src/components/organisms/pupil/Oakinfo/OakInfo.tsx
- src/components/organisms/pupil/Oakinfo/__snapshots__/OakInfo.test.tsx.snap
- src/components/organisms/pupil/OakinfoButton/OakInfoButton.test.tsx
- src/components/organisms/pupil/OakinfoButton/OakInfoButton.tsx
- src/components/organisms/pupil/OakinfoButton/__snapshots__/OakInfoButton.test.tsx.snap
> Fix/pupil 701/tooltip aria labels 2

- src/components/molecules/OakModal/OakModal.test.tsx
- src/components/molecules/OakModal/OakModal.tsx
- src/components/molecules/OakModal/__snapshots__/OakModal.test.tsx.snap
`document.body` isn't available during SSR, so this would blow up.
This commit adds an awful `useEffect` which flips an `isMounted` boolean which we can use to determine if we're rendering on the client while avoiding a server->client markup mismatch warning. *groan*
- …
> fix: `OakModal` blowing up when doing SSR

- src/components/molecules/OakModal/OakModal.tsx
- src/components/organisms/OakCookieBanner/OakCookieBanner.tsx
- src/components/organisms/OakCookieConsent/OakCookieConsent.stories.tsx
- src/components/organisms/OakCookieConsent/OakCookieConsent.tsx
- src/components/organisms/OakCookieSettingsModal/OakCookieSettingsModal.tsx
- src/styles/helpers/parseZindex.test.tsx
- src/styles/theme/zIndex.ts
the z-index of 99999 caused that the banner to be rendered on top of the settings modal. This commit restores the original values while adding an option to set a stacking context for the entire `OakCookieConsent` component.
This ensures that the entire component can be stacked according to the needs of the host app while keeping the internal stacking order encapsulated.
**before**
**after**
https://github.com/oaknational/oak-components/assets/122096/610007d8-2578-4580-a41e-57e575df9ef3
- Check [naming …
> fix: `OakCookieSettingsModal` being stacked behind `OakCookieBanner`

- src/components/atoms/InternalTooltip/InternalTooltip.tsx
- src/components/molecules/OakTooltip/OakTooltip.tsx
[x] Missing exports for Oak components
[x] Accidental export of Internal components
[x] Snapshots of unexpected components have been modified
[x] Circular dependencies
[x] Code duplication (via not using base components)
[x] Non-functional storybook for this or related components
[x] Sensitve files changed eg. …
> chore: refactor id on OakTooltip

- src/components/organisms/OakCookieConsent/OakCookieConsent.stories.tsx
- src/components/organisms/OakCookieConsent/OakCookieConsent.tsx
- src/components/organisms/OakCookieConsentProvider/OakCookieConsentProvider.test.tsx
- src/components/organisms/OakCookieConsentProvider/OakCookieConsentProvider.tsx
- src/components/organisms/OakCookieSettingsModal/OakCookieSettingsModal.stories.tsx
- src/components/organisms/OakCookieSettingsModal/OakCookieSettingsModal.test.tsx
- src/components/organisms/OakCookieSettingsModal/OakCookieSettingsModal.tsx
BREAKING CHANGE: this brings the prop names inline with those in oak-consent-client making integration easier.
This will make it much cleaner to integrate the UI with the client. Since these components are highly unlikely to be used with anything but oak-consent-client, it makes sense that they have things named consistently and APIs that match.
This change means that an integrating component will now look something like:
```typescript
const { state, logConsents } = useOakConsent();
return (
<OakCookieConsentProvider
policyConsents={state.policyConsents}
onConsentChange={logConsents}
>
<OakCookieConsent
policyURL="/cookie-policy"
isFixed
/>
</OakCookieConsentProvider>
);
```
- Check [component …
> feat!: rename props in consent ui

- src/components/organisms/pupil/Oakinfo/OakInfo.test.tsx
- src/components/organisms/pupil/Oakinfo/OakInfo.tsx
- src/components/organisms/pupil/Oakinfo/__snapshots__/OakInfo.test.tsx.snap
> [PUPIL-801] Pa11y issue and make id passed into the OakInfo to avoid id conflicts

- src/components/molecules/OakModal/OakModal.tsx
- src/components/organisms/OakCookieBanner/OakCookieBanner.tsx
- src/components/organisms/OakCookieConsent/OakCookieConsent.tsx
- src/styles/theme/zIndex.ts
> [ENG-813] Consent banner stacked in front of modals

- src/components/organisms/OakHeaderHero/OakHeaderHero.tsx
> feat: prop for passing cms image

- src/components/molecules/OakButtonAsRadioGroup/OakButtonAsRadioGroup.stories.tsx
- src/components/molecules/OakButtonAsRadioGroup/OakButtonAsRadioGroup.test.tsx
- src/components/molecules/OakButtonAsRadioGroup/OakButtonAsRadioGroup.tsx
- src/components/molecules/OakButtonAsRadioGroup/__snapshots__/OakButtonAsRadioGroup.test.tsx.snap
- src/components/molecules/OakButtonAsRadioGroup/index.ts
- src/components/molecules/OakSecondaryButtonAsRadio/OakSecondaryButtonAsRadio.stories.tsx
- src/components/molecules/OakSecondaryButtonAsRadio/OakSecondaryButtonAsRadio.test.tsx
- src/components/molecules/OakSecondaryButtonAsRadio/OakSecondaryButtonAsRadio.tsx
- src/components/molecules/OakSecondaryButtonAsRadio/__snapshots__/OakSecondaryButtonAsRadio.test.tsx.snap
- src/components/molecules/OakSecondaryButtonAsRadio/index.ts
- src/components/molecules/index.ts
- src/components/organisms/pupil/OakPupilJourneyList/OakPupilJourneyList.stories.tsx
- src/components/organisms/pupil/OakPupilJourneyList/OakPupilJourneyList.tsx
- src/components/organisms/pupil/OakPupilJourneyList/__snapshots__/OakPupilJourneyList.test.tsx.snap
- src/components/organisms/pupil/OakPupilJourneyPreviousLessons/OakPupilJourneyPreviousLessons.tsx
- src/components/organisms/pupil/OakPupilJourneyPreviousLessons/__snapshots__/OakPupilJourneyPreviousLessons.test.tsx.snap
> feat: oak-secondary-button-as-radio

- src/components/organisms/pupil/OakPupilJourneyList/OakPupilJourneyList.tsx
> feat: added filter slot and refactored

- README.md
It was not abundantly clear that the example used the App router rather than Pages. We could also add a working example for the Pages router.
- …
> chore: correct missing `OakGlobalStyle` import and add a note to the example

- src/components/molecules/OakInlineBanner/OakInlineBanner.stories.tsx
- src/components/molecules/OakInlineBanner/OakInlineBanner.test.tsx
- src/components/molecules/OakInlineBanner/OakInlineBanner.tsx
- src/components/molecules/OakInlineBanner/__snapshots__/OakInlineBanner.test.tsx.snap
- src/components/molecules/OakInlineBanner/index.ts
- src/components/molecules/index.ts
- src/image-map.ts
> [PUPIL-838] Add OakInlineBanner component and tests

- src/components/organisms/OakHeaderHero/OakHeaderHero.tsx
- src/components/organisms/OakHeaderHero/__snapshots__/OakHeaderHero.test.tsx.snap
> fix: change heading tag to h1

- src/components/organisms/pupil/OakQuizHint/OakQuizHint.tsx
> [PUPIL-864] Updating the quiz hint tooltip position

- src/components/organisms/pupil/OakLessonBottomNav/OakLessonBottomNav.tsx
- src/components/organisms/pupil/OakLessonBottomNav/__snapshots__/OakLessonBottomNav.test.tsx.snap
- src/components/organisms/pupil/OakQuizHint/OakQuizHint.stories.tsx
- src/components/organisms/pupil/OakQuizHint/OakQuizHint.test.tsx
- src/components/organisms/pupil/OakQuizHint/OakQuizHint.tsx
- src/components/organisms/pupil/OakQuizHint/__snapshots__/OakQuizHint.test.tsx.snap
> [PUPIL-864] Fix accessibility issue on OakQuizHint

- src/components/molecules/OakJauntyAngleLabel/OakJauntyAngleLabel.stories.tsx
- src/components/molecules/OakJauntyAngleLabel/OakJauntyAngleLabel.test.tsx
- src/components/molecules/OakJauntyAngleLabel/OakJauntyAngleLabel.tsx
- src/components/molecules/OakJauntyAngleLabel/__snapshots__/OakJauntyAngleLabel.test.tsx.snap
- src/components/molecules/OakJauntyAngleLabel/index.ts
> PUPIL-873 feat(angle-label): add oak jaunty angle label component to storybook

- src/components/organisms/pupil/OakLessonLayout/OakLessonLayout.tsx
> [PUPIL-866] Add wobbly borders to OakLessonLayout

- src/components/organisms/pupil/OakLessonLayout/OakLessonLayout.stories.tsx
- src/components/organisms/pupil/OakLessonLayout/OakLessonLayout.tsx
- src/components/organisms/pupil/OakLessonTopNav/OakLessonTopNav.tsx
- src/image-map.ts
- Sensitive files changed eg. atoms, or style …
> [PUPIL-797] New pupil lesson svg backgrounds and colours

- src/components/organisms/pupil/OakLessonLayout/OakLessonLayout.tsx
> fix: missed marking 2 OakLessonLayoutProps props as optional

- src/components/organisms/pupil/OakLessonLayout/OakLessonLayout.tsx
> fix: update so that pupil lesson svg backgrounds only show on large displays

- src/components/CopyPasteThisComponent/CopyPasteThisComponent.stories.tsx
- src/components/organisms/OakPagination/OakPagination.stories.tsx
- src/components/organisms/OakPagination/OakPagination.test.tsx
- src/components/organisms/OakPagination/OakPagination.tsx
- src/components/organisms/OakPagination/__snapshots__/OakPagination.test.tsx.snap
- src/components/organisms/OakPagination/index.ts
- src/components/organisms/OakPagination/utils.ts
> LESQ-955: OakPagination component 

- src/components/organisms/pupil/quiz/OakQuizResultItem/OakQuizResultItem.tsx
- src/components/organisms/pupil/quiz/OakQuizResultItem/__snapshots__/OakQuizResultItem.test.tsx.snap
> fix: alignment and minHeight for flex box

- src/components/organisms/shared/OakPagination/OakPagination.stories.tsx
- src/components/organisms/shared/OakPagination/OakPagination.test.tsx
- src/components/organisms/shared/OakPagination/OakPagination.tsx
> fix: remove state from pagination component

- src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.stories.tsx
- src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.test.tsx
- src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.tsx
- src/components/organisms/teacher/OakUnitListItem/__snapshots__/OakUnitListItem.test.tsx.snap
- src/components/organisms/teacher/OakUnitListOptionalityItem/OakUnitListOptionalityItem.tsx
- src/components/organisms/teacher/OakUnitListOptionalityItem/__snapshots__/OakUnitListOptionalityItem.test.tsx.snap
- src/components/organisms/teacher/OakUnitsContainer/OakUnitsContainer.stories.tsx
- src/components/organisms/teacher/OakUnitsContainer/__snapshots__/OakUnitsContainer.test.tsx.snap
- src/components/organisms/teacher/OakUnitsHeader/OakUnitsHeader.tsx
- src/components/organisms/teacher/OakUnitsHeader/__snapshots__/OakUnitsHeader.test.tsx.snap
> Feat add expired counts to unit cards

- src/components/organisms/teacher/OakUnitListOptionalityItem/OakUnitListOptionalityItem.stories.tsx
- src/components/organisms/teacher/OakUnitListOptionalityItem/OakUnitListOptionalityItem.tsx
- src/components/organisms/teacher/OakUnitListOptionalityItem/__snapshots__/OakUnitListOptionalityItem.test.tsx.snap
> LESQ-1008: Align yearTitle

- src/components/molecules/OakRadioButton/OakRadioButton.stories.tsx
- src/components/molecules/OakRadioButton/OakRadioButton.tsx
> feat: add required prop to radio button

- src/components/atoms/OakFieldset/OakFieldset.stories.tsx
- src/components/atoms/OakFieldset/OakFieldset.test.tsx
- src/components/atoms/OakFieldset/OakFieldset.tsx
- src/components/atoms/OakFieldset/__snapshots__/OakFieldset.test.tsx.snap
- src/components/atoms/OakFieldset/index.ts
> Oakfieldset component

- src/components/molecules/OakLoadingSpinner/OakLoadingSpinner.stories.tsx
- src/components/molecules/OakLoadingSpinner/OakLoadingSpinner.test.tsx
- src/components/molecules/OakLoadingSpinner/OakLoadingSpinner.tsx
> feat: add a configurable delay to OakLoadingSpinner

- src/components/organisms/pupil/quiz/OakQuizCounter/OakQuizCounter.tsx
- src/components/organisms/pupil/quiz/OakQuizCounter/__snapshots__/OakQuizCounter.test.tsx.snap
> Fix/pupil 882/color contrast

- src/components/organisms/pupil/lesson/OakLessonVideoTranscript/OakLessonVideoTranscript.tsx
- src/components/organisms/pupil/lesson/OakLessonVideoTranscript/__snapshots__/OakLessonVideoTranscript.test.tsx.snap
> Feat/pupil 837/make transcript accessible

- src/components/organisms/shared/Oakinfo/OakInfo.tsx
- src/components/organisms/shared/Oakinfo/__snapshots__/OakInfo.test.tsx.snap
> Fix/pupil 820/add aria label info

- src/components/molecules/OakScaleImageButton/OakScaleImageButton.stories.tsx
- src/components/molecules/OakScaleImageButton/OakScaleImageButton.test.tsx
- src/components/molecules/OakScaleImageButton/OakScaleImageButton.tsx
- src/components/molecules/OakScaleImageButton/__snapshots__/OakScaleImageButton.test.tsx.snap
- src/components/molecules/OakScaleImageButton/index.ts
- src/components/molecules/index.ts
- src/image-map.ts
> Feat/pupil 855/scale image button

- src/components/molecules/OakSolidBorderAccordion/OakSolidBorderAccordion.tsx
- src/components/molecules/OakSolidBorderAccordion/__snapshots__/OakSolidBorderAccordion.test.tsx.snap
- src/components/organisms/shared/OakMediaClipList/OakMediaClipList.stories.tsx
- src/components/organisms/shared/OakMediaClipList/__snapshots__/OakMediaClipList.test.tsx.snap
- src/components/organisms/shared/OakVideoTranscript/OakVideoTranscript.stories.tsx
- src/components/organisms/shared/OakVideoTranscript/OakVideoTranscript.test.tsx
- src/components/organisms/shared/OakVideoTranscript/OakVideoTranscript.tsx
- src/components/organisms/shared/OakVideoTranscript/__snapshots__/OakVideoTranscript.test.tsx.snap
> CTC-57 Style updates for media page

- src/components/molecules/InternalChevronAccordion/InternalChevronAccordion.tsx
- src/components/molecules/InternalChevronAccordion/__snapshots__/InternalChevronAccordion.test.tsx.snap
- src/components/molecules/OakMediaClipListAccordion/OakMediaClipListAccordion.stories.tsx
- src/components/molecules/OakMediaClipListAccordion/OakMediaClipListAccordion.test.tsx
- src/components/molecules/OakMediaClipListAccordion/OakMediaClipListAccordion.tsx
- src/components/molecules/OakMediaClipListAccordion/__snapshots__/OakMediaClipListAccordion.test.tsx.snap
- src/components/molecules/OakMediaClipListAccordion/index.ts
- src/components/molecules/OakOutlineAccordion/__snapshots__/OakOutlineAccordion.test.tsx.snap
- src/components/molecules/OakSolidBorderAccordion/index.ts
- src/components/organisms/pupil/browse/OakPupilJourneyUnitsFilter/__snapshots__/OakPupilJourneyUnitsFilter.test.tsx.snap
- src/components/organisms/shared/OakMediaClipList/OakMediaClipList.tsx
- src/components/organisms/shared/OakMediaClipList/__snapshots__/OakMediaClipList.test.tsx.snap
- src/components/organisms/shared/OakVideoTranscript/OakVideoTranscript.tsx
> CTC-97 updates to OakMediaClipList and OakVideoTranscript component

- src/components/atoms/InternalAccordion/InternalAccordion.tsx
- src/components/molecules/InternalChevronAccordion/InternalChevronAccordion.test.tsx
- src/components/molecules/InternalChevronAccordion/InternalChevronAccordion.tsx
- src/components/molecules/InternalChevronAccordion/__snapshots__/InternalChevronAccordion.test.tsx.snap
- src/components/molecules/OakMediaClipListAccordion/__snapshots__/OakMediaClipListAccordion.test.tsx.snap
- src/components/molecules/OakOutlineAccordion/__snapshots__/OakOutlineAccordion.test.tsx.snap
- src/components/molecules/OakSolidBorderAccordion/__snapshots__/OakSolidBorderAccordion.test.tsx.snap
- src/components/organisms/pupil/browse/OakPupilJourneyUnitsFilter/__snapshots__/OakPupilJourneyUnitsFilter.test.tsx.snap
- src/components/organisms/shared/OakMediaClipList/OakMediaClipList.stories.tsx
- src/components/organisms/shared/OakMediaClipList/__snapshots__/OakMediaClipList.test.tsx.snap
> CTC-98 Add shadow to OakMediaClipList accordion

- src/components/atoms/OakFlex/OakFlex.tsx
- src/components/atoms/OakImage/OakImage.tsx
- src/components/molecules/OakBackLink/OakBackLink.tsx
- src/components/molecules/OakBackLink/__snapshots__/OakBackLink.test.tsx.snap
- src/components/organisms/pupil/lesson/OakLessonTopNav/__snapshots__/OakLessonTopNav.test.tsx.snap
- src/image-map.ts
- src/styles/theme/color.ts
- src/styles/theme/index.ts
- src/styles/theme/spacing.ts
> PUPIL-1160 Changes needed to retire Svg component in OWA

- src/components/organisms/shared/OakQuote/OakQuote.stories.tsx
- src/components/organisms/shared/OakQuote/OakQuote.tsx
- src/components/organisms/shared/OakQuote/__snapshots__/OakQuote.test.tsx.snap
> fix: show colour line in OakQuote

- src/components/atoms/InternalRadio/InternalRadio.test.tsx
- src/components/atoms/InternalRadio/InternalRadio.tsx
- src/components/atoms/InternalRadio/__snapshots__/InternalRadio.test.tsx.snap
- src/components/organisms/curriculum/OakRadioAsButton/OakRadioAsButton.test.tsx
- src/components/organisms/curriculum/OakRadioAsButton/OakRadioAsButton.tsx
- src/components/organisms/curriculum/OakRadioAsButton/__snapshots__/OakRadioAsButton.test.tsx.snap
> Fix OakRadioAsButton state handling

- src/components/organisms/curriculum/OakRadioAsButton/OakRadioAsButton.stories.tsx
- src/components/organisms/curriculum/OakRadioAsButton/OakRadioAsButton.test.tsx
- src/components/organisms/curriculum/OakRadioAsButton/OakRadioAsButton.tsx
- src/components/organisms/curriculum/OakRadioAsButton/__snapshots__/OakRadioAsButton.test.tsx.snap
> Allow `<OakRadioAsButton/>` to accept `value` from `<OakRadioGroup/>`

- src/components/molecules/OakCodeRenderer/OakCodeRenderer.tsx
- src/components/organisms/pupil/lesson/OakLessonBottomNav/OakLessonBottomNav.stories.tsx
- src/components/organisms/pupil/quiz/OakQuizHint/OakQuizHint.stories.tsx
Add typography props to code renderer (this needs to be done for the OWA PR for https://www.notion.so/oaknationalacademy/Oak-Components-Update-OakQuizFeedback-and-OakQuizHint-to-use-CodeRender-Code-in-quizzes-Pupil-view-17c26cc4e1b180afae83d4e4fad933aa)
Bottom example in storybook here:
https://deploy-preview-372--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-pupil-quiz-oakquizhint--docs
and bottom onein this one:
https://deploy-preview-372--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-pupil-lesson-oaklessonbottomnav--docs
> Add typography props to code renderer

- .github/workflows/verify.yml
The `SonarSource/sonarcloud-github-action` is deprecated. The newer, drop in replacement, `SonarSource/sonarqube-scan-action` is available.
- Moved from `sonarcloud-github-action` to `sonarqube-scan-action`
- Moved from using `master` as a version to a specific version (to stop any breaking changes immediately impacting project workflows)
Fixes ENG-1129
1. Check SonarQube scans are running successfully.
> ENG-1129: Update the SonarQube action in GitHub workflows

- src/components/molecules/OakCodeRenderer/OakCodeRenderer.tsx
Added OakBox props to OakCodeRenderer so we can control the margins in OWA through props - no visual changes here
https://deploy-preview-373--lively-meringue-8ebd43.netlify.app/?path=/docs/components-molecules-oakcoderenderer--docs
> CTC-126 Use code renderer wrapper in relevant components

- src/image-map.ts
> feat: add english language svg to image map

- src/components/molecules/OakCarousel/OakCarousel.tsx
> fix: carousel stretches to fit container

- src/components/organisms/teacher/OakUnitsContainer/__snapshots__/OakUnitsContainer.test.tsx.snap
- src/components/organisms/teacher/OakUnitsHeader/OakUnitsHeader.tsx
- src/components/organisms/teacher/OakUnitsHeader/__snapshots__/OakUnitsHeader.test.tsx.snap
> Feat/lesq 1284/unit title casing [LESQ-1284]

- src/components/molecules/InternalLink/InternalLink.tsx
- src/components/molecules/InternalLink/__snapshots__/InternalLink.test.tsx.snap
- src/components/molecules/OakFilterDrawer/__snapshots__/OakFilterDrawer.test.tsx.snap
- src/components/molecules/OakInlineBanner/__snapshots__/OakInlineBanner.test.tsx.snap
- src/components/molecules/OakLink/OakLink.stories.tsx
- src/components/molecules/OakLink/__snapshots__/OakLink.test.tsx.snap
- src/components/molecules/OakSecondaryLink/__snapshots__/OakSecondaryLink.test.tsx.snap
- src/components/organisms/shared/OakCookieBanner/__snapshots__/OakCookieBanner.test.tsx.snap
- src/components/organisms/shared/OakCookieConsent/__snapshots__/OakCookieConsent.test.tsx.snap
- src/components/organisms/shared/OakHeaderHero/__snapshots__/OakHeaderHero.test.tsx.snap
- src/components/organisms/shared/OakPagination/__snapshots__/OakPagination.test.tsx.snap
- src/components/organisms/teacher/OakTeacherNotesModal/__snapshots__/OakTeacherNotesModal.test.tsx.snap
- src/components/organisms/teacher/OakTertiaryOLNav/__snapshots__/OakTertiaryOLNav.test.tsx.snap
> CTC-155: align OakLink with icon

- src/image-map.ts
> feat: add new looping line icon to image map

- src/components/molecules/InternalShadowRectButton/__snapshots__/InternalShadowRectButton.test.tsx.snap
- src/styles/theme/color.ts
> feat: add mint color filters to oakColorFilterTokens

- src/components/molecules/OakLinkCard/OakLinkCard.stories.tsx
- src/components/molecules/OakLinkCard/OakLinkCard.test.tsx
- src/components/molecules/OakLinkCard/OakLinkCard.tsx
- src/components/molecules/OakLinkCard/__snapshots__/OakLinkCard.test.tsx.snap
- src/components/molecules/OakLinkCard/index.ts
- src/components/molecules/OakPromoTag/OakPromoTag.tsx
- src/components/molecules/OakPromoTag/__snapshots__/OakPromoTag.test.tsx.snap
- src/components/molecules/index.ts
- src/components/organisms/teacher/OakUnitsContainer/__snapshots__/OakUnitsContainer.test.tsx.snap
- src/components/organisms/teacher/OakUnitsHeader/__snapshots__/OakUnitsHeader.test.tsx.snap
- src/image-map.ts
- src/styles/theme/dropShadow.ts
> Feat/pupil 1221/oak link card

- src/components/organisms/teacher/OakUnitsContainer/OakUnitsContainer.stories.tsx
- src/components/organisms/teacher/OakUnitsContainer/OakUnitsContainer.tsx
- src/components/organisms/teacher/OakUnitsHeader/OakUnitsHeader.tsx
`OakUnitsContainer` amendments to accommodate for the swimming units
added new props:
- `isCustomUnit`
-  `customHeadingText`
- `bannerText`
https://www.notion.so/oaknationalacademy/oak-components-amend-OakUnitsContainer-component-1ce26cc4e1b180ff95bae9d84c0f1a6c
https://deploy-preview-398--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-teacher-oakunitscontainer--docs
> feat: OakUnitsContainer amendments

- src/components/molecules/OakInlineBanner/OakInlineBanner.stories.tsx
- src/components/molecules/OakInlineBanner/OakInlineBanner.test.tsx
- src/components/molecules/OakInlineBanner/OakInlineBanner.tsx
- src/components/molecules/OakInlineBanner/__snapshots__/OakInlineBanner.test.tsx.snap
- src/components/organisms/curriculum/OakDownloadsJourneyChildSubjectTierSelector/__snapshots__/OakDownloadsJourneyChildSubjectTierSelector.test.tsx.snap
> feat: added warning type InlineBanner, added large variant and minor tweaks to match design system

- src/components/molecules/OakInlineBanner/OakInlineBanner.tsx
- src/components/molecules/OakInlineBanner/__snapshots__/OakInlineBanner.test.tsx.snap
> OakInlineBanner CTA content stacking in Firefox fix

- src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.tsx
- src/components/organisms/teacher/OakUnitListItem/__snapshots__/OakUnitListItem.test.tsx.snap
> fix: use align stretch to fill background on firefox

- src/components/organisms/pupil/browse/OakPupilJourneySubjectButton/OakPupilJourneySubjectButton.tsx
- src/components/organisms/pupil/browse/OakPupilJourneySubjectButton/__snapshots__/OakPupilJourneySubjectButton.test.tsx.snap
- src/components/organisms/pupil/quiz/OakQuizResultItem/OakQuizResultItem.tsx
> fix: add test ids to icons where they are being used in tests in OWA

- src/components/molecules/OakToast/OakToast.stories.tsx
- src/components/molecules/OakToast/OakToast.test.tsx
- src/components/molecules/OakToast/OakToast.tsx
- src/components/molecules/OakToast/__snapshots__/OakToast.test.tsx.snap
- src/components/molecules/OakToast/index.ts
- src/components/molecules/index.ts
> Feat/lesq 1337/toast component [LESQ-1337]

- src/components/organisms/teacher/OakTeacherNotesModal/OakTeacherNotesModal.stories.tsx
- src/components/organisms/teacher/OakTeacherNotesModal/OakTeacherNotesModal.test.tsx
- src/components/organisms/teacher/OakTeacherNotesModal/OakTeacherNotesModal.tsx
- src/components/organisms/teacher/OakTeacherNotesModal/__snapshots__/OakTeacherNotesModal.test.tsx.snap
> feat: added ability to insert footer content and disable share button on teacher modal

- src/components/molecules/OakToast/OakToast.stories.tsx
- src/components/molecules/OakToast/OakToast.test.tsx
- src/components/molecules/OakToast/OakToast.tsx
> fix: make OakToast duration extendible

- src/components/organisms/teacher/OakInlineRegistrationBanner/OakInlineRegistrationBanner.test.tsx
- src/components/organisms/teacher/OakInlineRegistrationBanner/OakInlineRegistrationBanner.tsx
- src/components/organisms/teacher/OakInlineRegistrationBanner/__snapshots__/OakInlineRegistrationBanner.test.tsx.snap
> fix: autocomplete email addresses in registration banner component

- src/components/molecules/OakSaveCount/OakSaveCount.stories.tsx
- src/components/molecules/OakSaveCount/OakSaveCount.test.tsx
- src/components/molecules/OakSaveCount/OakSaveCount.tsx
- src/components/molecules/OakSaveCount/__snapshots__/OakSaveCount.test.tsx.snap
> Feat/lesq 1415/save count [LESQ-1415]

- src/components/molecules/OakToast/OakToast.tsx
- src/components/organisms/curriculum/OakRadioAsButton/OakRadioAsButton.tsx
- src/components/organisms/shared/OakMediaClip/OakMediaClip.tsx
- src/components/organisms/shared/OakMediaClip/__snapshots__/OakMediaClip.test.tsx.snap
- src/components/organisms/teacher/OakSearchFilterCheckBox/OakSearchFilterCheckBox.tsx
> Don't pass non-DOM attributes down to DOM

- src/components/organisms/pupil/lesson/InternalReviewAccordion/InternalReviewAccordion.tsx
- src/components/organisms/pupil/lesson/InternalReviewAccordion/__snapshots__/InternalReviewAccordion.test.tsx.snap
> Remove `isOpen` as attribute from DOM node in `<InternalReviewAccordion/>`

- src/components/molecules/OakSaveCount/OakSaveCount.tsx
- src/components/molecules/OakSaveCount/__snapshots__/OakSaveCount.test.tsx.snap
> feat: dont show number on mobile sizes

- src/components/organisms/shared/OakSideMenuNav/OakSideMenuNav.test.tsx
- src/components/organisms/shared/OakSideMenuNav/OakSideMenuNav.tsx
- src/components/organisms/shared/OakSideMenuNav/__snapshots__/OakSideMenuNav.test.tsx.snap
> Feat/lesq 1338/oak side menu nav updates

- src/components/organisms/shared/OakHeaderHero/OakHeaderHero.tsx
Check to see if the component still renders without author props in the deployment
I've made the author props optional and added some conditional logic, so that the tests in [this PR](https://github.com/oaknational/Oak-Web-Application/pull/3457/files#diff-49c5055ea6c55e3d4f0304c8442b5211579528e7f21d5cdf72b828fb0401771b) pass.
- `OakHeaderHero` must render without `author` props, i.e. if no `author` props are provided that section will be omitted
> feat: add optional props to OakHeaderHero component

- src/components/molecules/OakTagFunctional/OakTagFunctional.stories.tsx
- src/components/molecules/OakTagFunctional/OakTagFunctional.tsx
> feat: updated OakTagFunctional so you can use span or label element

- src/components/molecules/OakLinkCard/OakLinkCard.stories.tsx
- src/components/molecules/OakLinkCard/OakLinkCard.test.tsx
- src/components/molecules/OakLinkCard/OakLinkCard.tsx
- src/components/molecules/OakLinkCard/__snapshots__/OakLinkCard.test.tsx.snap
> Feat: hasAnimation prop for OakLinkCard component

- src/components/molecules/OakAccordion/OakAccordion.tsx
- src/components/organisms/shared/OakCookieSettingsModal/OakCookieSettingsModal.tsx
> feat: add correct header tag to OakCookieSettingsModal

- src/components/molecules/OakFieldError/OakFieldError.tsx
> Added missing `alt="Error"` to `<OakFieldError/>`

- src/components/molecules/OakRadioButton/OakRadioButton.tsx
- src/components/organisms/pupil/quiz/OakQuizRadioButton/__snapshots__/OakQuizRadioButton.test.tsx.snap
> Fix size/spacing of `<OakRadioButton/>` when styled

- src/components/atoms/InternalRadioWrapper/InternalRadioWrapper.tsx
- src/components/molecules/OakDownloadCard/OakDownloadCard.stories.tsx
- src/components/molecules/OakDownloadCard/OakDownloadCard.tsx
- src/components/molecules/OakDownloadCard/__snapshots__/OakDownloadCard.test.tsx.snap
> Allow wrapped height to stretch in <OakDownloadCard/>

- src/image-map.ts
- Sensitive files changed eg. atoms, or style …
> Add curriculum plan and national curriculum spreadsheet icons

- src/components/molecules/OakFormInput/OakFormInput.stories.tsx
- src/components/molecules/OakFormInputWithLabels/OakFormInputWithLabels.stories.tsx
- src/components/molecules/OakFormInputWithLabels/OakFormInputWithLabels.tsx
- src/components/organisms/create/OakCaptionSearch/OakCaptionSearch.stories.tsx
- src/components/organisms/create/OakCaptionSearch/OakCaptionSearch.tsx
- src/components/organisms/index.ts
> fix: added a defaultValue prop from formInput upwards

- src/components/atoms/InternalRadioWrapper/InternalRadioWrapper.tsx
- src/components/atoms/InternalRadioWrapper/__snapshots__/InternalRadioWrapper.test.tsx.snap
- src/components/molecules/OakRadioButton/__snapshots__/OakRadioButton.test.tsx.snap
- src/components/molecules/OakRadioGroup/__snapshots__/OakRadioGroup.test.tsx.snap
- src/components/organisms/curriculum/OakDownloadsJourneyChildSubjectTierSelector/__snapshots__/OakDownloadsJourneyChildSubjectTierSelector.test.tsx.snap
- src/components/organisms/pupil/quiz/OakQuizRadioButton/__snapshots__/OakQuizRadioButton.test.tsx.snap
> Fix/lesq 1557/radio button input

- package-lock.json
- src/components/molecules/OakHandDrawnHR/OakHandDrawnHR.stories.tsx
- src/components/molecules/OakHandDrawnHR/OakHandDrawnHR.tsx
- src/components/molecules/OakHandDrawnHR/__snapshots__/OakHandDrawnHR.test.tsx.snap
- src/components/molecules/OakOutlineAccordion/__snapshots__/OakOutlineAccordion.test.tsx.snap
- src/components/organisms/pupil/browse/OakPupilJourneyUnitsFilter/__snapshots__/OakPupilJourneyUnitsFilter.test.tsx.snap
- src/components/organisms/pupil/quiz/OakQuizCounter/OakQuizCounter.tsx
- src/components/organisms/pupil/quiz/OakQuizCounter/__snapshots__/OakQuizCounter.test.tsx.snap
- src/styles/utils/flexStyle.ts
> Feat/pupil 1335/focusable false aria hidden
